sudo: required

language: c

services:
  - docker

matrix:
  include:
  - env: IMG=quid2/x64-ubuntu-stack CMD="stack test --resolver lts-11.22"
    
  - env: IMG=quid2/x32-ubuntu-cabal CMD="cabal install --only-dependencies --enable-tests;cabal test"

before_install:
- docker pull $IMG

script:
- docker run -it $IMG bash -c 'git clone https://github.com/Quid2/flat;cd flat;${!CMD}'