sudo: required

language: c

services:
  - docker

matrix:
  include:
  - env: IMG=quid2/x32-ubuntu-cabal CMD="cabal install --only-dependencies --enable-tests;cabal test"
  
  - env: IMG=quid2/x64-ubuntu-stack CMD="stack test --resolver lts-6.35"

  - env: IMG=quid2/x64-ubuntu-stack CMD="stack test --resolver lts-11.22"
  
  - env: IMG=quid2/x64-ubuntu-ghcjs CMD="stack test --stack-yaml stack-ghcjs.yaml"

before_install:
- docker pull $IMG

script:
- PKG=flat
- docker run -it $IMG bash -c "git clone https://github.com/Quid2/flat;cd $PKG;${CMD}"